---
version: '3'


services:
  gsas:
    image: gsas:conda
    build:
      context: ../gsas
      dockerfile: Containerfile-conda
    command: conda run -n GSASII --no-capture-output uvicorn bluesky_adaptive.server:app --host 0.0.0.0 --root-path /gsas
    environment:
      - TILED_API_KEY=$TILED_API_KEY
      - BS_AGENT_STARTUP_SCRIPT_PATH=/src/pdf-agents/pdf_agents/startup_scripts/mmm5-tax-day/gsas.py
    volumes:
      - type: bind
        source: ../pdf_agents
        target: /src/pdf-agents/pdf_agents
        read_only: true
      - type: bind
        source: /etc/bluesky/kafka.yml
        target: /etc/bluesky/kafka.yml
        read_only: true

  kmeans-gsas:
    image: bluesky:latest
    command: uvicorn bluesky_adaptive.server:app --host 0.0.0.0
    environment:
      - TILED_API_KEY=$TILED_API_KEY
      - BS_AGENT_STARTUP_SCRIPT_PATH=/src/pdf-agents/pdf_agents/startup_scripts/mmm5-tax-day/gsas.py
    volumes:
      - type: bind
        source: ../pdf_agents
        target: /src/pdf-agents/pdf_agents
        read_only: true
      - type: bind
        source: /etc/bluesky/kafka.yml
        target: /etc/bluesky/kafka.yml
        read_only: true
    depends_on:
      gsas:
        condition: service_started
    
  proxy:
    image: docker.io/nginx
    init: true
    ports:
      - "11973:11973"
    volumes:
      - type: bind
        source: ../containers/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ../containers/nginx/locs.d
        target: /etc/nginx/locs.d
        read_only: true
      - type: bind
        source: ../containers/nginx/html
        target: /var/www/html
        read_only: true
    depends_on:
      gsas:
        condition: service_started
      kmeans-gsas:
        condition: service_started

