---
version: '3'


services:
  gsas:
    image: gsas:conda
    build:
      context: ../gsas
      dockerfile: Containerfile-conda
    command: /bin/bash -c "export BS_AGENT_STARTUP_SCRIPT_PATH=/src/pdf-agents/pdf_agents/startup_scripts/mmm5-tax-day/gsas.py && exec conda run -n GSASII --no-capture-output uvicorn bluesky_adaptive.server:app"
    volumes:
      - type: bind
        source: ../pdf_agents
        target: /src/pdf-agents/pdf_agents
        read_only: true

  kmeans-gsas:
    image: bluesky:latest
    command: /bin/bash -c "BS_AGENT_STARTUP_SCRIPT_PATH=/src/pdf-agents/pdf_agents/startup_scripts/mmm5-tax-day/kmeans-gsas.py uvicorn bluesky_adaptive.server:app"
    volumes:
      - type: bind
        source: ../pdf_agents
        target: /src/pdf-agents/pdf_agents
        read_only: true
    depends_on:
      gsas:
        condition: service_started
    
  proxy:
    image: docker.io/nginx
    init: true
    ports:
      - "11973:11973"
    volumes:
      - type: bind
        source: ../containers/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ../containers/nginx/locs.d
        target: /etc/nginx/locs.d
        read_only: true
      - type: bind
        source: ../containers/nginx/html
        target: /var/www/html
        read_only: true
    depends_on:
      gsas:
        condition: service_started
      kmeans-gsas:
        condition: service_started

