---
version: '3'


services:
  gsas:
    image: gsas:conda
    build:
      context: ../gsas
      dockerfile: Containerfile-conda
    command: conda run -n GSASII --no-capture-output uvicorn bluesky_adaptive.server:app
    env:
      - BS_AGENT_STARTUP_SCRIPT_PATH: /src/pdf-agents/pdf_agents/startup_scripts/mmm5-tax-day/gsas.py
    volumes:
      - type: ro
        source: ../pdf_agents
        target: /src/pdf-agents/pdf_agents

  kmeans-gsas:
    image: bluesky:latest
    command: uvicorn bluesky_adaptive.server:app
    env:
      - BS_AGENT_STARTUP_SCRIPT_PATH: /src/pdf-agents/pdf_agents/startup_scripts/mmm5-tax-day/kmeans-gsas.py
    volumes:
      - type: ro
        source: ../pdf_agents
        target: /src/pdf-agents/pdf_agents
    depends_on:
      gsas:
        condition: service_started
    
  proxy:
    image: docker.io/nginx
    init: true
    ports:
      - "127.0.0.1:11973:11973"
    volumes:
      - type: ro
        source: ../nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: ro
        source: ../nginx/locs.d
        target: /etc/nginx/locs.d
      - type: ro
        source: ../nginx/html
        target: /var/www/html
    depends_on:
      gsas:
        condition: service_started
      kmeans-gsas:
        condition: service_started


  


